FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y build-essential software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.10 python3-pip python3-setuptools python3-distutils && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip

WORKDIR /usr/src/app

EXPOSE 5000

COPY ./src/main/docker/python/socketio_whsiperx.py ./socketio_whsiperx.py
COPY ./requirements.txt ./requirements.txt

RUN apt-get update

RUN pip install Flask --ignore-installed
RUN pip install Flask-SocketIO --ignore-installed
RUN apt-get install espeak -y

RUN pip install -r requirements.txt

RUN pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu118

RUN apt-get install ffmpeg -y

ENTRYPOINT [ "python" ]
CMD ["socketio_whsiperx.py"]
